version: '3'
services:
  demo:
    image: "registry.virginia.com:5000/demo:latest"
    ports:
     - 8082:8080
    networks:
      internal_network:
         aliases:
               - demo
networks:
  internal_network:
    driver: overlay
    ipam:
      driver: default


